import Head from "next/head";
import Footer from "../src/components/Footer/Footer";
import Hero from "../src/components/Hero/Hero";
import Navbar from "../src/components/Navbar/Navbar";
import OpenHour from "../src/components/OpenHour/OpenHour";
import Service from "../src/components/ServiceSection/Service";
import Testimonial from "../src/components/Testimonials/Testimonial";

export default function Home() {
  return (
    <>
      <Head>
        <title>Streethairlab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Service />
      <OpenHour />
      <Testimonial />
      <Footer />
    </>
  );
}
